/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.CtrlMenu_Ingreso;
import Modelo.Datos_Categoria_Ingreso;
import static Vista.Ventana_Login.usuario_id;
import java.awt.Color;

/**
 *
 * @author Usuario
 */
public class Ventana_Registrar_Ingreso extends javax.swing.JFrame {

    int xMouseCrema, yMouseCrema;

    public Ventana_Registrar_Ingreso() {
        initComponents();

        txtRegistrarIngreso.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        btnAtras = new javax.swing.JLabel();
        cbxTipoIngreso = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtBienvenida = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMONTO_INGRESO = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFECHA_INGRESO = new javax.swing.JTextField();
        btnRegistrarIngreso = new javax.swing.JPanel();
        txtRegistrarIngreso = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 48, 60));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(36, 48, 60));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitTxt.setFont(new java.awt.Font("FG Virgil", 1, 48)); // NOI18N
        exitTxt.setForeground(new java.awt.Color(62, 82, 102));
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("x");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });
        header.add(exitTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, -10, 50, 50));

        btnAtras.setFont(new java.awt.Font("FG Virgil", 1, 30)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(62, 82, 102));
        btnAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAtras.setText("<---");
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAtrasMouseExited(evt);
            }
        });
        header.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 40));

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 40));

        cbxTipoIngreso.setBackground(new java.awt.Color(36, 48, 60));
        cbxTipoIngreso.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        cbxTipoIngreso.setForeground(new java.awt.Color(255, 255, 255));
        cbxTipoIngreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(cbxTipoIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 270, 40));

        jLabel7.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(26, 177, 136));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("('AÑO'-'MES'-'DIA')");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 290, 30));

        txtBienvenida.setBackground(new java.awt.Color(255, 255, 255));
        txtBienvenida.setFont(new java.awt.Font("Roboto Mono", 1, 30)); // NOI18N
        txtBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        txtBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBienvenida.setText("REGISTRAR INGRESO");
        jPanel1.add(txtBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 400, 50));

        jLabel8.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("TIPO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 70, 30));

        txtMONTO_INGRESO.setBackground(new java.awt.Color(36, 48, 60));
        txtMONTO_INGRESO.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        txtMONTO_INGRESO.setForeground(new java.awt.Color(255, 255, 255));
        txtMONTO_INGRESO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        txtMONTO_INGRESO.setCaretColor(new java.awt.Color(255, 255, 255));
        txtMONTO_INGRESO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtMONTO_INGRESOMousePressed(evt);
            }
        });
        txtMONTO_INGRESO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMONTO_INGRESOActionPerformed(evt);
            }
        });
        jPanel1.add(txtMONTO_INGRESO, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 270, 40));

        jLabel9.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("MONTO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 80, 30));

        txtFECHA_INGRESO.setBackground(new java.awt.Color(36, 48, 60));
        txtFECHA_INGRESO.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        txtFECHA_INGRESO.setForeground(new java.awt.Color(255, 255, 255));
        txtFECHA_INGRESO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        txtFECHA_INGRESO.setCaretColor(new java.awt.Color(255, 255, 255));
        txtFECHA_INGRESO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFECHA_INGRESOMousePressed(evt);
            }
        });
        jPanel1.add(txtFECHA_INGRESO, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 270, 40));

        btnRegistrarIngreso.setBackground(new java.awt.Color(26, 177, 136));
        btnRegistrarIngreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRegistrarIngreso.setFont(new java.awt.Font("Roboto Mono", 1, 22)); // NOI18N
        txtRegistrarIngreso.setForeground(new java.awt.Color(255, 255, 255));
        txtRegistrarIngreso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRegistrarIngreso.setText("<html><center>Registrar<br>Ingreso<html>");
        btnRegistrarIngreso.add(txtRegistrarIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 60));

        jPanel1.add(btnRegistrarIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 180, 60));

        jLabel10.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("FECHA");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        //exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.red);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        //exitBtn.setBackground(new Color(36, 48, 60));
        exitTxt.setForeground(new Color(62, 82, 102));
    }//GEN-LAST:event_exitTxtMouseExited

    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
        this.dispose();
        Ventana_Ingreso frm_ingreso = new Ventana_Ingreso();
        CtrlMenu_Ingreso ctrlmenu_ingreso = new CtrlMenu_Ingreso(frm_ingreso);
        ctrlmenu_ingreso.iniciar();
        frm_ingreso.setVisible(true);
        usuario_id = Ventana_Login.getUsuarioId();
        System.out.println("2: " + usuario_id);
    }//GEN-LAST:event_btnAtrasMouseClicked

    private void btnAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseEntered
        btnAtras.setForeground(new Color(12, 133, 153));
    }//GEN-LAST:event_btnAtrasMouseEntered

    private void btnAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseExited
        btnAtras.setForeground(new Color(62, 82, 102));
    }//GEN-LAST:event_btnAtrasMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x1 = evt.getXOnScreen() - xMouseCrema;
        int y1 = evt.getYOnScreen() - yMouseCrema;
        this.setLocation(x1, y1);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouseCrema = evt.getXOnScreen() - this.getX();
        yMouseCrema = evt.getYOnScreen() - this.getY();
    }//GEN-LAST:event_headerMousePressed

    private void txtMONTO_INGRESOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMONTO_INGRESOActionPerformed

    }//GEN-LAST:event_txtMONTO_INGRESOActionPerformed

    private void txtMONTO_INGRESOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMONTO_INGRESOMousePressed
        txtMONTO_INGRESO.setForeground(Color.white);
    }//GEN-LAST:event_txtMONTO_INGRESOMousePressed

    private void txtFECHA_INGRESOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFECHA_INGRESOMousePressed
        txtFECHA_INGRESO.setForeground(Color.white);
    }//GEN-LAST:event_txtFECHA_INGRESOMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Registrar_Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Registrar_Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Registrar_Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Registrar_Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Registrar_Ingreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAtras;
    public javax.swing.JPanel btnRegistrarIngreso;
    public javax.swing.JComboBox<Datos_Categoria_Ingreso> cbxTipoIngreso;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JLabel txtBienvenida;
    public javax.swing.JTextField txtFECHA_INGRESO;
    public javax.swing.JTextField txtMONTO_INGRESO;
    public javax.swing.JLabel txtRegistrarIngreso;
    // End of variables declaration//GEN-END:variables
}
