/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.CtrlMenu_Opciones;
import Controlador.CtrlVentana_Ahorros;
import Controlador.CtrlVentana_Inversion;
import Controlador.Ctrl_Metas;
import Modelo.Consulta_Obtener_Dinero_Ahorrado;
import Modelo.Consulta_Obtener_Dinero_Inversion;
import Modelo.Consulta_Obtener_Suma_Egresos;
import Modelo.Consulta_Obtener_Suma_Ingresos;
import Modelo.Consulta_Obtener_Suma_Recursos_Asignados_Metas;
import static Vista.Ventana_Login.usuario_id;

/**
 *
 * @author Usuario
 */
public class Ventana_Gestionar_Recursos extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Gestionar_Recursos
     */
    public Ventana_Gestionar_Recursos() {
        initComponents();
        this.setTitle("Opciones");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnMetas = new javax.swing.JButton();
        btnAhorro = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnInversion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(36, 48, 60));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMetas.setBackground(new java.awt.Color(0, 102, 102));
        btnMetas.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        btnMetas.setForeground(new java.awt.Color(255, 255, 255));
        btnMetas.setText("Metas");
        btnMetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetasActionPerformed(evt);
            }
        });
        jPanel3.add(btnMetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 300, -1));

        btnAhorro.setBackground(new java.awt.Color(0, 102, 102));
        btnAhorro.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        btnAhorro.setForeground(new java.awt.Color(255, 255, 255));
        btnAhorro.setText("Ahorro (Chanchito)");
        btnAhorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAhorroActionPerformed(evt);
            }
        });
        jPanel3.add(btnAhorro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 300, -1));

        btnAtras.setBackground(new java.awt.Color(0, 102, 102));
        btnAtras.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel3.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 162, -1));

        btnInversion.setBackground(new java.awt.Color(0, 102, 102));
        btnInversion.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        btnInversion.setForeground(new java.awt.Color(255, 255, 255));
        btnInversion.setText("Inversión");
        btnInversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInversionActionPerformed(evt);
            }
        });
        jPanel3.add(btnInversion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 300, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetasActionPerformed
        this.dispose();

        Ventana_Metas frm_metas = new Ventana_Metas();
        Ctrl_Metas ctrl_metas = new Ctrl_Metas(frm_metas);

        ctrl_metas.iniciar();
        frm_metas.setVisible(true);
    }//GEN-LAST:event_btnMetasActionPerformed

    private void btnAhorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAhorroActionPerformed

        this.dispose();
        Ventana_Ahorros frm_ahorros = new Ventana_Ahorros();
        Consulta_Obtener_Suma_Ingresos consulta_obtener_suma_ingreso = new Consulta_Obtener_Suma_Ingresos();
        Consulta_Obtener_Suma_Egresos consulta_obtener_suma_egreso = new Consulta_Obtener_Suma_Egresos();
        Consulta_Obtener_Suma_Recursos_Asignados_Metas consulta_obtener_suma_recursos_asignados = new Consulta_Obtener_Suma_Recursos_Asignados_Metas();
        Consulta_Obtener_Dinero_Ahorrado consulta_obtener_dinero_ahorrado = new Consulta_Obtener_Dinero_Ahorrado();
        Consulta_Obtener_Dinero_Inversion consulta_obtener_dinero_inversion = new Consulta_Obtener_Dinero_Inversion();
        CtrlVentana_Ahorros ctrlventana_ahorros = new CtrlVentana_Ahorros(
                frm_ahorros,
                consulta_obtener_suma_ingreso,
                consulta_obtener_suma_egreso,
                consulta_obtener_suma_recursos_asignados,
                consulta_obtener_dinero_ahorrado,
                consulta_obtener_dinero_inversion,
                usuario_id);

        ctrlventana_ahorros.iniciar();
        frm_ahorros.setVisible(true);


    }//GEN-LAST:event_btnAhorroActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.dispose();
        Ventana_Opciones frm_opciones = new Ventana_Opciones();
        CtrlMenu_Opciones ctrlmenu_opciones = new CtrlMenu_Opciones(frm_opciones);
        ctrlmenu_opciones.iniciar();
        frm_opciones.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnInversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInversionActionPerformed

        this.dispose();
        Ventana_Inversion frm_inversion = new Ventana_Inversion();
        Consulta_Obtener_Suma_Ingresos consulta_obtener_suma_ingreso = new Consulta_Obtener_Suma_Ingresos();
        Consulta_Obtener_Suma_Egresos consulta_obtener_suma_egreso = new Consulta_Obtener_Suma_Egresos();
        Consulta_Obtener_Suma_Recursos_Asignados_Metas consulta_obtener_suma_recursos_asignados = new Consulta_Obtener_Suma_Recursos_Asignados_Metas();
        Consulta_Obtener_Dinero_Ahorrado consulta_obtener_dinero_ahorrado = new Consulta_Obtener_Dinero_Ahorrado();
        Consulta_Obtener_Dinero_Inversion consulta_obtener_dinero_inversion = new Consulta_Obtener_Dinero_Inversion();

        CtrlVentana_Inversion ctrlventana_inversion = new CtrlVentana_Inversion(
                frm_inversion,
                consulta_obtener_suma_ingreso,
                consulta_obtener_suma_egreso,
                consulta_obtener_suma_recursos_asignados,
                consulta_obtener_dinero_ahorrado,
                consulta_obtener_dinero_inversion,
                usuario_id);

        ctrlventana_inversion.iniciar();
        frm_inversion.setVisible(true);


    }//GEN-LAST:event_btnInversionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAhorro;
    public javax.swing.JButton btnAtras;
    public javax.swing.JButton btnInversion;
    public javax.swing.JButton btnMetas;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
