/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.CtrlMenu_Egreso;
import Modelo.Conexion;
import static Vista.Ventana_Login.usuario_id;
import java.awt.Color;
import java.awt.Graphics;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Personal
 */
public class Ventana_Categorizar_Egreso extends javax.swing.JFrame {

    // Variables para almacenar los totales de las categorías
    private double TotalEgresosComida;
    private double TotalEgresosTrasporte;
    private double TotalEgresosEntretenimiento;
    private double TotalEgresosServicios;
    private double TotalEgresosGastosVarios;

    public Ventana_Categorizar_Egreso() {
        initComponents();
        this.setLocationRelativeTo(null);

        try {
            PreparedStatement ps1 = null;  // Primer PreparedStatement
            PreparedStatement ps2 = null;  // Segundo PreparedStatement
            PreparedStatement ps3 = null;
            PreparedStatement ps4 = null;
            PreparedStatement ps5 = null;
            ResultSet rs1 = null;         // Primer ResultSet
            ResultSet rs2 = null;         // Segundo ResultSet
            ResultSet rs3 = null;
            ResultSet rs4 = null;
            ResultSet rs5 = null;
            Conexion conn = new Conexion();
            java.sql.Connection con = conn.getConexion();

            String sql1 = "SELECT SUM(MONTO_EGRESO) AS TotalEgresosComida FROM egreso WHERE TIPO_EGRESO = 'Comida' AND usuario_id = ?";
            ps1 = con.prepareStatement(sql1);
            ps1.setInt(1, usuario_id);
            rs1 = ps1.executeQuery();

            String sql2 = "SELECT SUM(MONTO_EGRESO) AS TotalEgresosTrasporte FROM egreso WHERE TIPO_EGRESO = 'Transporte' AND usuario_id = ?";
            ps2 = con.prepareStatement(sql2);
            ps2.setInt(1, usuario_id);
            rs2 = ps2.executeQuery();

            String sql3 = "SELECT SUM(MONTO_EGRESO) AS TotalEgresosEntretenimiento FROM egreso WHERE TIPO_EGRESO = 'Entretenimiento' AND usuario_id = ?";
            ps3 = con.prepareStatement(sql3);
            ps3.setInt(1, usuario_id);
            rs3 = ps3.executeQuery();

            String sql4 = "SELECT SUM(MONTO_EGRESO) AS TotalEgresosServicios FROM egreso WHERE TIPO_EGRESO = 'Servicios' AND usuario_id = ?";
            ps4 = con.prepareStatement(sql4);
            ps4.setInt(1, usuario_id);
            rs4 = ps4.executeQuery();

            String sql5 = "SELECT SUM(MONTO_EGRESO) AS TotalEgresosGastosVarios FROM egreso WHERE TIPO_EGRESO LIKE 'Gastos Varios%' AND usuario_id = ?";
            ps5 = con.prepareStatement(sql5);
            ps5.setInt(1, usuario_id);
            rs5 = ps5.executeQuery();

            TotalEgresosComida = 0.0;
            TotalEgresosTrasporte = 0.0;
            TotalEgresosEntretenimiento = 0.0;
            TotalEgresosServicios = 0.0;
            TotalEgresosGastosVarios = 0.0;

            if (rs1.next() && rs2.next() && rs3.next() && rs4.next() && rs5.next()) {
                TotalEgresosComida = rs1.getDouble("TotalEgresosComida");
                System.out.println("TotalEgresosComida: " + TotalEgresosComida);

                TotalEgresosTrasporte = rs2.getDouble("TotalEgresosTrasporte");
                System.out.println("TotalEgresosTrasporte: " + TotalEgresosTrasporte);

                TotalEgresosEntretenimiento = rs3.getDouble("TotalEgresosEntretenimiento");
                System.out.println("TotalEgresosEntretenimiento: " + TotalEgresosEntretenimiento);

                TotalEgresosServicios = rs4.getDouble("TotalEgresosServicios");
                System.out.println("TotalEgresosServicios: " + TotalEgresosServicios);

                TotalEgresosGastosVarios = rs5.getDouble("TotalEgresosGastosVarios");
                System.out.println("TotalEgresosGastosVarios: " + TotalEgresosGastosVarios);
            }
            txt_comida.setText(String.valueOf(TotalEgresosComida));
            txt_transporte.setText(String.valueOf(TotalEgresosTrasporte));
            txt_entretenimiento.setText(String.valueOf(TotalEgresosEntretenimiento));
            txt_servicios.setText(String.valueOf(TotalEgresosServicios));
            txt_gastosvarios.setText(String.valueOf(TotalEgresosGastosVarios));

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pizarra = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_comida = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_transporte = new javax.swing.JTextField();
        btn_g = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_entretenimiento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_servicios = new javax.swing.JTextField();
        txt_gastosvarios = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pizarra.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("Categorización de Egresos");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Comida:");

        txt_comida.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Transporte:");

        txt_transporte.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        btn_g.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_g.setText("Graficar");
        btn_g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Entretenimiento:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Servicios:");

        txt_entretenimiento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Gastos Varios:");

        txt_servicios.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txt_gastosvarios.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        btnAtras.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAtras.setText("<-");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pizarraLayout = new javax.swing.GroupLayout(pizarra);
        pizarra.setLayout(pizarraLayout);
        pizarraLayout.setHorizontalGroup(
            pizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pizarraLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(pizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(38, 38, 38)
                .addGroup(pizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pizarraLayout.createSequentialGroup()
                        .addGroup(pizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_comida, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_transporte, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_gastosvarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                .addComponent(txt_servicios)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pizarraLayout.createSequentialGroup()
                        .addComponent(txt_entretenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                        .addComponent(btn_g)
                        .addGap(102, 102, 102))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pizarraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        pizarraLayout.setVerticalGroup(
            pizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pizarraLayout.createSequentialGroup()
                .addGroup(pizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pizarraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(pizarraLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAtras)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 397, Short.MAX_VALUE)
                .addGroup(pizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_comida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(pizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_transporte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_entretenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_g))
                .addGap(26, 26, 26)
                .addGroup(pizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_servicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_gastosvarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pizarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pizarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed

        this.dispose();
        Ventana_Egreso frm_egreso = new Ventana_Egreso();
        CtrlMenu_Egreso ctrlmenu_egreso = new CtrlMenu_Egreso(frm_egreso);
        ctrlmenu_egreso.iniciar();
        frm_egreso.setVisible(true);


    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btn_gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gActionPerformed

        try {
            Graphics lapiz = pizarra.getGraphics();

            double double_comida = TotalEgresosComida;
            double double_transporte = TotalEgresosTrasporte;
            double double_entretenimiento = TotalEgresosEntretenimiento;
            double double_servicios = TotalEgresosServicios;
            double double_gastosvarios = TotalEgresosGastosVarios;

            double suma_valores = double_comida + double_transporte + double_entretenimiento + double_servicios + double_gastosvarios;

            double grados_comida = double_comida * 360 / suma_valores;
            double grados_transporte = double_transporte * 360 / suma_valores;
            double grados_entretenimiento = double_entretenimiento * 360 / suma_valores;
            double grados_servicios = double_servicios * 360 / suma_valores;
            double grados_gastosvarios = double_gastosvarios * 360 / suma_valores;

            lapiz.setColor(Color.decode("#EE4266"));
            lapiz.fillArc(100, 80, 360, 360, 0, (int) grados_comida);
            lapiz.fillRect(550, 120, 20, 20);
            lapiz.drawString("Comida", 580, 135);

            lapiz.setColor(Color.decode("#2A1E5C"));
            lapiz.fillArc(100, 80, 360, 360, (int) grados_comida, (int) grados_transporte);
            lapiz.fillRect(550, 150, 20, 20);
            lapiz.drawString("Transporte", 580, 165);

            lapiz.setColor(Color.decode("#4381C1"));
            lapiz.fillArc(100, 80, 360, 360, (int) (grados_comida + grados_transporte), (int) grados_entretenimiento);
            lapiz.fillRect(550, 180, 20, 20);
            lapiz.drawString("Entretenimiento", 580, 195);

            lapiz.setColor(Color.decode("#2D2D2A"));
            lapiz.fillArc(100, 80, 360, 360, (int) (grados_comida + grados_transporte + grados_entretenimiento), (int) grados_servicios);
            lapiz.fillRect(550, 210, 20, 20);
            lapiz.drawString("Servicios", 580, 225);

            lapiz.setColor(Color.decode("#3CBBB1"));
            lapiz.fillArc(100, 80, 360, 360, (int) (grados_comida + grados_transporte + grados_entretenimiento + grados_servicios), (int) grados_gastosvarios);
            lapiz.fillRect(550, 240, 20, 20);
            lapiz.drawString("Gastos Varios", 580, 255);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: Verifique su información ingresada");
        }

    }//GEN-LAST:event_btn_gActionPerformed

    public void obtenergrafico() {

        try {

            Graphics lapiz = pizarra.getGraphics();

            int int_comida = (int) TotalEgresosComida;
            int int_transporte = (int) TotalEgresosTrasporte;
            int int_entretenimiento = (int) TotalEgresosEntretenimiento;
            int int_servicios = (int) TotalEgresosServicios;
            int int_gastosvarios = (int) TotalEgresosGastosVarios;

            int suma_valores = int_comida + int_transporte + int_entretenimiento + int_servicios + int_gastosvarios;

            int grados_comida = int_comida * 360 / suma_valores;
            int grados_transporte = int_transporte * 360 / suma_valores;
            int grados_entretenimiento = int_entretenimiento * 360 / suma_valores;
            int grados_servicios = int_servicios * 360 / suma_valores;
            int grados_gastosvarios = int_gastosvarios * 360 / suma_valores;

            lapiz.setColor(Color.decode("#EE4266"));
            lapiz.fillArc(100, 80, 360, 360, 0, grados_comida);
            lapiz.fillRect(550, 120, 20, 20);
            lapiz.drawString("Comida", 580, 135);

            lapiz.setColor(Color.decode("#2A1E5C"));
            lapiz.fillArc(100, 80, 360, 360, grados_comida, grados_transporte);
            lapiz.fillRect(550, 150, 20, 20);
            lapiz.drawString("Transporte", 580, 165);

            lapiz.setColor(Color.decode("#4381C1"));
            lapiz.fillArc(100, 80, 360, 360, grados_comida + grados_transporte, grados_entretenimiento);
            lapiz.fillRect(550, 180, 20, 20);
            lapiz.drawString("Entretenimiento", 580, 195);

            lapiz.setColor(Color.decode("#2D2D2A"));
            lapiz.fillArc(100, 80, 360, 360, grados_comida + grados_transporte + grados_entretenimiento, grados_servicios);
            lapiz.fillRect(550, 210, 20, 20);
            lapiz.drawString("Servicios", 580, 225);

            lapiz.setColor(Color.decode("#3CBBB1"));
            lapiz.fillArc(100, 80, 360, 360, grados_comida + grados_transporte + grados_entretenimiento + grados_servicios, grados_gastosvarios);
            lapiz.fillRect(550, 240, 20, 20);
            lapiz.drawString("Gastos Varios", 580, 255);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: Verifique su información ingresada");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAtras;
    private javax.swing.JButton btn_g;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel pizarra;
    private javax.swing.JTextField txt_comida;
    private javax.swing.JTextField txt_entretenimiento;
    private javax.swing.JTextField txt_gastosvarios;
    private javax.swing.JTextField txt_servicios;
    private javax.swing.JTextField txt_transporte;
    // End of variables declaration//GEN-END:variables
}
