/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.CtrlMenu_Opciones;
import Controlador.CtrlVentana_Ahorros;
import Controlador.CtrlVentana_Inversion;
import Controlador.Ctrl_Metas;
import Modelo.Consulta_Obtener_Dinero_Ahorrado;
import Modelo.Consulta_Obtener_Dinero_Inversion;
import Modelo.Consulta_Obtener_Suma_Egresos;
import Modelo.Consulta_Obtener_Suma_Ingresos;
import Modelo.Consulta_Obtener_Suma_Recursos_Asignados_Metas;
import static Vista.Ventana_Login.usuario_id;

/**
 *
 * @author Usuario
 */
public class Ventana_Gestionar_Recursos extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Gestionar_Recursos
     */
    public Ventana_Gestionar_Recursos() {
        initComponents();
        this.setTitle("Opciones");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnMetas = new javax.swing.JButton();
        btnAhorro = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnInversion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMetas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnMetas.setText("Metas");
        btnMetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetasActionPerformed(evt);
            }
        });

        btnAhorro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAhorro.setText("Ahorro (Chanchito)");
        btnAhorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAhorroActionPerformed(evt);
            }
        });

        btnAtras.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnInversion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnInversion.setText("Inversión");
        btnInversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInversionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnMetas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAhorro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInversion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(btnMetas)
                .addGap(18, 18, 18)
                .addComponent(btnAhorro)
                .addGap(18, 18, 18)
                .addComponent(btnInversion)
                .addGap(41, 41, 41)
                .addComponent(btnAtras)
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetasActionPerformed
        this.dispose();

        Ventana_Metas frm_metas = new Ventana_Metas();
        Ctrl_Metas ctrl_metas = new Ctrl_Metas(frm_metas);

        ctrl_metas.iniciar();
        frm_metas.setVisible(true);
    }//GEN-LAST:event_btnMetasActionPerformed

    private void btnAhorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAhorroActionPerformed

        this.dispose();
        Ventana_Ahorros frm_ahorros = new Ventana_Ahorros();
        Consulta_Obtener_Suma_Ingresos consulta_obtener_suma_ingreso = new Consulta_Obtener_Suma_Ingresos();
        Consulta_Obtener_Suma_Egresos consulta_obtener_suma_egreso = new Consulta_Obtener_Suma_Egresos();
        Consulta_Obtener_Suma_Recursos_Asignados_Metas consulta_obtener_suma_recursos_asignados = new Consulta_Obtener_Suma_Recursos_Asignados_Metas();
        Consulta_Obtener_Dinero_Ahorrado consulta_obtener_dinero_ahorrado = new Consulta_Obtener_Dinero_Ahorrado();
        Consulta_Obtener_Dinero_Inversion consulta_obtener_dinero_inversion = new Consulta_Obtener_Dinero_Inversion();
        CtrlVentana_Ahorros ctrlventana_ahorros = new CtrlVentana_Ahorros(
                frm_ahorros,
                consulta_obtener_suma_ingreso,
                consulta_obtener_suma_egreso,
                consulta_obtener_suma_recursos_asignados,
                consulta_obtener_dinero_ahorrado,
                consulta_obtener_dinero_inversion,
                usuario_id);

        ctrlventana_ahorros.iniciar();
        frm_ahorros.setVisible(true);


    }//GEN-LAST:event_btnAhorroActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.dispose();
        Ventana_Opciones frm_opciones = new Ventana_Opciones();
        CtrlMenu_Opciones ctrlmenu_opciones = new CtrlMenu_Opciones(frm_opciones);
        ctrlmenu_opciones.iniciar();
        frm_opciones.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnInversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInversionActionPerformed

        this.dispose();
        Ventana_Inversion frm_inversion = new Ventana_Inversion();
        Consulta_Obtener_Suma_Ingresos consulta_obtener_suma_ingreso = new Consulta_Obtener_Suma_Ingresos();
        Consulta_Obtener_Suma_Egresos consulta_obtener_suma_egreso = new Consulta_Obtener_Suma_Egresos();
        Consulta_Obtener_Suma_Recursos_Asignados_Metas consulta_obtener_suma_recursos_asignados = new Consulta_Obtener_Suma_Recursos_Asignados_Metas();
        Consulta_Obtener_Dinero_Ahorrado consulta_obtener_dinero_ahorrado = new Consulta_Obtener_Dinero_Ahorrado();
        Consulta_Obtener_Dinero_Inversion consulta_obtener_dinero_inversion = new Consulta_Obtener_Dinero_Inversion();

        CtrlVentana_Inversion ctrlventana_inversion = new CtrlVentana_Inversion(
                frm_inversion,
                consulta_obtener_suma_ingreso,
                consulta_obtener_suma_egreso,
                consulta_obtener_suma_recursos_asignados,
                consulta_obtener_dinero_ahorrado,
                consulta_obtener_dinero_inversion,
                usuario_id);

        ctrlventana_inversion.iniciar();
        frm_inversion.setVisible(true);


    }//GEN-LAST:event_btnInversionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAhorro;
    public javax.swing.JButton btnAtras;
    public javax.swing.JButton btnInversion;
    public javax.swing.JButton btnMetas;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
