/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Ctrl_Fijar_Egreso;
import Controlador.Ctrl_Fijar_Ingreso;
import Modelo.Consulta_Datos_Presupuestos;
import Modelo.Datos_Presupuestos;

/**
 *
 * @author Usuario
 */
public class Ventana_Opciones_Fijar_Presupuesto extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Opciones_Fijar_R
     */
    public Ventana_Opciones_Fijar_Presupuesto() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnFijarIngreso = new javax.swing.JButton();
        btnFijarEgreso = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 48, 60));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFijarIngreso.setBackground(new java.awt.Color(25, 113, 194));
        btnFijarIngreso.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        btnFijarIngreso.setForeground(new java.awt.Color(255, 255, 255));
        btnFijarIngreso.setText("Fijar Ingreso");
        btnFijarIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFijarIngresoActionPerformed(evt);
            }
        });
        jPanel1.add(btnFijarIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 230, 60));

        btnFijarEgreso.setBackground(new java.awt.Color(47, 158, 68));
        btnFijarEgreso.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        btnFijarEgreso.setForeground(new java.awt.Color(255, 255, 255));
        btnFijarEgreso.setText("Fijar Egreso");
        btnFijarEgreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFijarEgresoActionPerformed(evt);
            }
        });
        jPanel1.add(btnFijarEgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 230, 60));

        btnAtras.setBackground(new java.awt.Color(0, 153, 153));
        btnAtras.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 162, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFijarIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFijarIngresoActionPerformed

        this.dispose();

        Datos_Presupuestos datos = new Datos_Presupuestos();
        Consulta_Datos_Presupuestos consulta = new Consulta_Datos_Presupuestos();
        Ventana_Fijar_Ingreso frm_fijar_ingreso = new Ventana_Fijar_Ingreso();
        Ctrl_Fijar_Ingreso ctrl_fijar_ingreso = new Ctrl_Fijar_Ingreso(datos, consulta, frm_fijar_ingreso);

        ctrl_fijar_ingreso.iniciar();
        frm_fijar_ingreso.setVisible(true);

    }//GEN-LAST:event_btnFijarIngresoActionPerformed

    private void btnFijarEgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFijarEgresoActionPerformed
        
        this.dispose();

        Datos_Presupuestos datos = new Datos_Presupuestos();
        Consulta_Datos_Presupuestos consulta = new Consulta_Datos_Presupuestos();
        Ventana_Fijar_Egreso frm_fijar_egreso = new Ventana_Fijar_Egreso();
        Ctrl_Fijar_Egreso ctrl_fijar_egreso = new Ctrl_Fijar_Egreso(datos, consulta, frm_fijar_egreso);

        ctrl_fijar_egreso.iniciar();
        frm_fijar_egreso.setVisible(true);
        
        
    }//GEN-LAST:event_btnFijarEgresoActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed

        this.dispose();
        Ventana_Opciones_Presupuesto opciones_presupuesto = new Ventana_Opciones_Presupuesto();
        opciones_presupuesto.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Opciones_Fijar_Presupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Opciones_Fijar_Presupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Opciones_Fijar_Presupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Opciones_Fijar_Presupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Opciones_Fijar_Presupuesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAtras;
    public javax.swing.JButton btnFijarEgreso;
    public javax.swing.JButton btnFijarIngreso;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
