/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Usuario
 */
public class Ventana_Metas extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Metas
     */
    public Ventana_Metas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnCrearMeta = new javax.swing.JButton();
        btnAsignarRecursos = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(36, 48, 60));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrearMeta.setBackground(new java.awt.Color(0, 102, 102));
        btnCrearMeta.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        btnCrearMeta.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearMeta.setText("Crear una Meta");
        btnCrearMeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearMetaActionPerformed(evt);
            }
        });
        jPanel3.add(btnCrearMeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 420, -1));

        btnAsignarRecursos.setBackground(new java.awt.Color(0, 102, 102));
        btnAsignarRecursos.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        btnAsignarRecursos.setForeground(new java.awt.Color(255, 255, 255));
        btnAsignarRecursos.setText("Asignar recursos a una meta");
        btnAsignarRecursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarRecursosActionPerformed(evt);
            }
        });
        jPanel3.add(btnAsignarRecursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        btnAtras.setBackground(new java.awt.Color(0, 102, 102));
        btnAtras.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel3.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 162, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearMetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearMetaActionPerformed

    }//GEN-LAST:event_btnCrearMetaActionPerformed

    private void btnAsignarRecursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarRecursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsignarRecursosActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed

    }//GEN-LAST:event_btnAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAsignarRecursos;
    public javax.swing.JButton btnAtras;
    public javax.swing.JButton btnCrearMeta;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
