/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.CtrlMenu_Opciones;
import Controlador.Ctrl_Crear_Recordatorio;
import Controlador.Ctrl_Ver_Recordatorios;
import Modelo.Consulta_Datos_Egreso;
import Modelo.Consulta_Datos_Recordatorio;
import Modelo.Consulta_Email_Notificacion;
import Modelo.Consulta_Obtener_Dinero_Ahorrado;
import Modelo.Consulta_Obtener_Dinero_Inversion;
import Modelo.Consulta_Obtener_Suma_Egresos;
import Modelo.Consulta_Obtener_Suma_Ingresos;
import Modelo.Consulta_Obtener_Suma_Recursos_Asignados_Metas;
import Modelo.Datos_Egreso;
import Modelo.Datos_Recordatorio;
import static Vista.Ventana_Login.usuario_id;

/**
 *
 * @author Usuario
 */
public class Ventana_Opciones_Recordatorio extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Opciones_Recordatorio
     */
    public Ventana_Opciones_Recordatorio() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCrearRecordatorio = new javax.swing.JButton();
        btnVerRecordatorios = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 48, 60));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrearRecordatorio.setBackground(new java.awt.Color(0, 102, 102));
        btnCrearRecordatorio.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        btnCrearRecordatorio.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearRecordatorio.setText("Crear Recordatorio");
        btnCrearRecordatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearRecordatorioActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearRecordatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 470, -1));

        btnVerRecordatorios.setBackground(new java.awt.Color(0, 102, 102));
        btnVerRecordatorios.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        btnVerRecordatorios.setForeground(new java.awt.Color(255, 255, 255));
        btnVerRecordatorios.setText("Ver mis Recordatorios");
        btnVerRecordatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerRecordatoriosActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerRecordatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 470, -1));

        btnAtras.setBackground(new java.awt.Color(0, 102, 102));
        btnAtras.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 162, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearRecordatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearRecordatorioActionPerformed
        this.dispose();

        Datos_Recordatorio datos_recordatorio = new Datos_Recordatorio();
        Consulta_Datos_Recordatorio consulta_recordatorio = new Consulta_Datos_Recordatorio();
        Consulta_Email_Notificacion email = new Consulta_Email_Notificacion();
        Ventana_Crear_Recordatorio vista = new Ventana_Crear_Recordatorio();

        Ctrl_Crear_Recordatorio ctrl_recordatorio = new Ctrl_Crear_Recordatorio(datos_recordatorio, consulta_recordatorio, email, vista, usuario_id);

        ctrl_recordatorio.iniciar();
        vista.setVisible(true);


    }//GEN-LAST:event_btnCrearRecordatorioActionPerformed

    private void btnVerRecordatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerRecordatoriosActionPerformed

        this.dispose();
        Datos_Egreso mod_egreso = new Datos_Egreso();
        Consulta_Obtener_Suma_Ingresos modC_sumaingreso = new Consulta_Obtener_Suma_Ingresos();
        Consulta_Obtener_Suma_Egresos modC_sumaegreso = new Consulta_Obtener_Suma_Egresos();
        Consulta_Datos_Egreso modC_egreso = new Consulta_Datos_Egreso();
        Consulta_Obtener_Suma_Recursos_Asignados_Metas modC_consulta_suma_recursos_asignados = new Consulta_Obtener_Suma_Recursos_Asignados_Metas();
        Consulta_Obtener_Dinero_Ahorrado consulta_obtener_dinero_ahorrado = new Consulta_Obtener_Dinero_Ahorrado();
        Consulta_Obtener_Dinero_Inversion consulta_obtener_dinero_inversion = new Consulta_Obtener_Dinero_Inversion();
        Consulta_Email_Notificacion email = new Consulta_Email_Notificacion();
        Ventana_Ver_Recordatorios vista = new Ventana_Ver_Recordatorios();
        Ctrl_Ver_Recordatorios ctrl = new Ctrl_Ver_Recordatorios(
                mod_egreso,
                modC_sumaingreso,
                modC_sumaegreso,
                modC_consulta_suma_recursos_asignados,
                consulta_obtener_dinero_ahorrado,
                consulta_obtener_dinero_inversion,
                modC_egreso,
                email,
                vista,
                usuario_id);

        ctrl.iniciar();
        vista.setVisible(true);

    }//GEN-LAST:event_btnVerRecordatoriosActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed

        this.dispose();

        Ventana_Opciones frm_opciones = new Ventana_Opciones();

        CtrlMenu_Opciones ctrlmenu_opciones = new CtrlMenu_Opciones(frm_opciones);

        ctrlmenu_opciones.iniciar();
        frm_opciones.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Opciones_Recordatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Opciones_Recordatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Opciones_Recordatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Opciones_Recordatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Opciones_Recordatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAtras;
    public javax.swing.JButton btnCrearRecordatorio;
    public javax.swing.JButton btnVerRecordatorios;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
