/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.CtrlMenu_Egreso;
import Modelo.Conexion;
import static Vista.Ventana_Login.usuario_id;
import java.awt.Color;
import java.awt.Graphics;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Personal
 */
public class Ventana_Categorizar_Egreso extends javax.swing.JFrame {

    // Variables para almacenar los totales de las categorías
    private double TotalEgresosComida;
    private double TotalEgresosTrasporte;
    private double TotalEgresosEntretenimiento;
    private double TotalEgresosServicios;
    private double TotalEgresosGastosVarios;

    public Ventana_Categorizar_Egreso() {
        initComponents();
        this.setLocationRelativeTo(null);

        llenar_datos();
        obtenergrafico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pizarra = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_comida = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_transporte = new javax.swing.JTextField();
        btn_g = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_entretenimiento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_servicios = new javax.swing.JTextField();
        txt_gastosvarios = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pizarra.setBackground(new java.awt.Color(36, 48, 60));
        pizarra.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pizarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Mono", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CATEGORIZACION EGRESO");
        pizarra.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Comida:");
        pizarra.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, -1, -1));

        txt_comida.setBackground(new java.awt.Color(36, 48, 60));
        txt_comida.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        txt_comida.setForeground(new java.awt.Color(255, 204, 0));
        txt_comida.setBorder(null);
        pizarra.add(txt_comida, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 190, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Transporte:");
        pizarra.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, -1, -1));

        txt_transporte.setBackground(new java.awt.Color(36, 48, 60));
        txt_transporte.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        txt_transporte.setForeground(new java.awt.Color(255, 204, 0));
        txt_transporte.setBorder(null);
        pizarra.add(txt_transporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, 190, -1));

        btn_g.setBackground(new java.awt.Color(0, 153, 153));
        btn_g.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_g.setForeground(new java.awt.Color(255, 255, 255));
        btn_g.setText("GRAFICAR");
        btn_g.setBorder(null);
        btn_g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gActionPerformed(evt);
            }
        });
        pizarra.add(btn_g, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 560, 140, 40));

        jLabel4.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Entretenimiento:");
        pizarra.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 590, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Servicios:");
        pizarra.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 650, -1, -1));

        txt_entretenimiento.setBackground(new java.awt.Color(36, 48, 60));
        txt_entretenimiento.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        txt_entretenimiento.setForeground(new java.awt.Color(255, 204, 0));
        txt_entretenimiento.setBorder(null);
        pizarra.add(txt_entretenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 590, 190, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gastos Varios:");
        pizarra.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 720, -1, -1));

        txt_servicios.setBackground(new java.awt.Color(36, 48, 60));
        txt_servicios.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        txt_servicios.setForeground(new java.awt.Color(255, 204, 0));
        txt_servicios.setBorder(null);
        pizarra.add(txt_servicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 650, 190, -1));

        txt_gastosvarios.setBackground(new java.awt.Color(36, 48, 60));
        txt_gastosvarios.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        txt_gastosvarios.setForeground(new java.awt.Color(255, 204, 0));
        txt_gastosvarios.setBorder(null);
        pizarra.add(txt_gastosvarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 720, 190, -1));

        btnAtras.setBackground(new java.awt.Color(36, 48, 60));
        btnAtras.setFont(new java.awt.Font("Roboto Mono", 1, 36)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(0, 153, 153));
        btnAtras.setText("<-");
        btnAtras.setAutoscrolls(true);
        btnAtras.setBorder(null);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        pizarra.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, -1));

        getContentPane().add(pizarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed

        this.dispose();
        Ventana_Egreso frm_egreso = new Ventana_Egreso();
        CtrlMenu_Egreso ctrlmenu_egreso = new CtrlMenu_Egreso(frm_egreso);
        ctrlmenu_egreso.iniciar();
        frm_egreso.setVisible(true);


    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btn_gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gActionPerformed
       
        obtenergrafico();

    }//GEN-LAST:event_btn_gActionPerformed

    
    public void llenar_datos(){
        try {
            PreparedStatement ps1 = null;  // Primer PreparedStatement
            PreparedStatement ps2 = null;  // Segundo PreparedStatement
            PreparedStatement ps3 = null;
            PreparedStatement ps4 = null;
            PreparedStatement ps5 = null;
            ResultSet rs1 = null;         // Primer ResultSet
            ResultSet rs2 = null;         // Segundo ResultSet
            ResultSet rs3 = null;
            ResultSet rs4 = null;
            ResultSet rs5 = null;
            Conexion conn = new Conexion();
            java.sql.Connection con = conn.getConexion();

            String sql1 = "SELECT SUM(MONTO_EGRESO) AS TotalEgresosComida FROM egreso WHERE TIPO_EGRESO LIKE 'Comida%' AND usuario_id = ?";
            ps1 = con.prepareStatement(sql1);
            ps1.setInt(1, usuario_id);
            rs1 = ps1.executeQuery();

            String sql2 = "SELECT SUM(MONTO_EGRESO) AS TotalEgresosTrasporte FROM egreso WHERE TIPO_EGRESO LIKE 'Transporte%' AND usuario_id = ?";
            ps2 = con.prepareStatement(sql2);
            ps2.setInt(1, usuario_id);
            rs2 = ps2.executeQuery();

            String sql3 = "SELECT SUM(MONTO_EGRESO) AS TotalEgresosEntretenimiento FROM egreso WHERE TIPO_EGRESO LIKE 'Entretenimiento%' AND usuario_id = ?";
            ps3 = con.prepareStatement(sql3);
            ps3.setInt(1, usuario_id);
            rs3 = ps3.executeQuery();

            String sql4 = "SELECT SUM(MONTO_EGRESO) AS TotalEgresosServicios FROM egreso WHERE TIPO_EGRESO LIKE 'Servicios%' AND usuario_id = ?";
            ps4 = con.prepareStatement(sql4);
            ps4.setInt(1, usuario_id);
            rs4 = ps4.executeQuery();

            String sql5 = "SELECT SUM(MONTO_EGRESO) AS TotalEgresosGastosVarios FROM egreso WHERE TIPO_EGRESO LIKE 'Gastos Varios%' AND usuario_id = ?";
            ps5 = con.prepareStatement(sql5);
            ps5.setInt(1, usuario_id);
            rs5 = ps5.executeQuery();

            TotalEgresosComida = 0.0;
            TotalEgresosTrasporte = 0.0;
            TotalEgresosEntretenimiento = 0.0;
            TotalEgresosServicios = 0.0;
            TotalEgresosGastosVarios = 0.0;

            if (rs1.next() && rs2.next() && rs3.next() && rs4.next() && rs5.next()) {
                TotalEgresosComida = rs1.getDouble("TotalEgresosComida");
                System.out.println("TotalEgresosComida: " + TotalEgresosComida);

                TotalEgresosTrasporte = rs2.getDouble("TotalEgresosTrasporte");
                System.out.println("TotalEgresosTrasporte: " + TotalEgresosTrasporte);

                TotalEgresosEntretenimiento = rs3.getDouble("TotalEgresosEntretenimiento");
                System.out.println("TotalEgresosEntretenimiento: " + TotalEgresosEntretenimiento);

                TotalEgresosServicios = rs4.getDouble("TotalEgresosServicios");
                System.out.println("TotalEgresosServicios: " + TotalEgresosServicios);

                TotalEgresosGastosVarios = rs5.getDouble("TotalEgresosGastosVarios");
                System.out.println("TotalEgresosGastosVarios: " + TotalEgresosGastosVarios);
            }
            txt_comida.setText(String.valueOf(TotalEgresosComida));
            txt_transporte.setText(String.valueOf(TotalEgresosTrasporte));
            txt_entretenimiento.setText(String.valueOf(TotalEgresosEntretenimiento));
            txt_servicios.setText(String.valueOf(TotalEgresosServicios));
            txt_gastosvarios.setText(String.valueOf(TotalEgresosGastosVarios));

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }
        
        
    }
    
    public void obtenergrafico() {

        try {
            Graphics lapiz = pizarra.getGraphics();

            double double_comida = TotalEgresosComida;
            double double_transporte = TotalEgresosTrasporte;
            double double_entretenimiento = TotalEgresosEntretenimiento;
            double double_servicios = TotalEgresosServicios;
            double double_gastosvarios = TotalEgresosGastosVarios;

            double suma_valores = double_comida + double_transporte + double_entretenimiento + double_servicios + double_gastosvarios;

            double grados_comida = double_comida * 360 / suma_valores;
            double grados_transporte = double_transporte * 360 / suma_valores;
            double grados_entretenimiento = double_entretenimiento * 360 / suma_valores;
            double grados_servicios = double_servicios * 360 / suma_valores;
            double grados_gastosvarios = double_gastosvarios * 360 / suma_valores;

            lapiz.setColor(Color.decode("#e06666"));
            lapiz.fillArc(100, 80, 360, 360, 0, (int) grados_comida);
            lapiz.fillRect(550, 120, 20, 20);
            lapiz.drawString("Comida", 580, 135);

            lapiz.setColor(Color.decode("#6fa8dc"));
            lapiz.fillArc(100, 80, 360, 360, (int) grados_comida, (int) grados_transporte);
            lapiz.fillRect(550, 150, 20, 20);
            lapiz.drawString("Transporte", 580, 165);

            lapiz.setColor(Color.decode("#ffd966"));
            lapiz.fillArc(100, 80, 360, 360, (int) (grados_comida + grados_transporte), (int) grados_entretenimiento);
            lapiz.fillRect(550, 180, 20, 20);
            lapiz.drawString("Entretenimiento", 580, 195);

            lapiz.setColor(Color.decode("#93c47d"));
            lapiz.fillArc(100, 80, 360, 360, (int) (grados_comida + grados_transporte + grados_entretenimiento), (int) grados_servicios);
            lapiz.fillRect(550, 210, 20, 20);
            lapiz.drawString("Servicios", 580, 225);

            lapiz.setColor(Color.decode("#76a5af"));
            lapiz.fillArc(100, 80, 360, 360, (int) (grados_comida + grados_transporte + grados_entretenimiento + grados_servicios), (int) grados_gastosvarios);
            lapiz.fillRect(550, 240, 20, 20);
            lapiz.drawString("Gastos Varios", 580, 255);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: Verifique su información ingresada");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAtras;
    private javax.swing.JButton btn_g;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel pizarra;
    private javax.swing.JTextField txt_comida;
    private javax.swing.JTextField txt_entretenimiento;
    private javax.swing.JTextField txt_gastosvarios;
    private javax.swing.JTextField txt_servicios;
    private javax.swing.JTextField txt_transporte;
    // End of variables declaration//GEN-END:variables
}
