/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Datos_Familia;

/**
 *
 * @author Usuario
 */
public class Ventana_Registrar_Egreso extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Registrar_Egreso
     */
    public Ventana_Registrar_Egreso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMONTO_EGRESO = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        ComboBoxTIPO_EGRESO = new javax.swing.JComboBox<>();
        btnAtras = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbxDestinoFamiliar = new javax.swing.JComboBox<>();
        txtBienvenida = new javax.swing.JLabel();
        jDateChooser = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 48, 60));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DESTINO FAMILIAR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FECHA DEL EGRESO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TIPO DEL EGRESO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        txtMONTO_EGRESO.setFont(new java.awt.Font("Roboto Mono", 0, 24)); // NOI18N
        txtMONTO_EGRESO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        txtMONTO_EGRESO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMONTO_EGRESOActionPerformed(evt);
            }
        });
        jPanel1.add(txtMONTO_EGRESO, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 290, 40));

        btnRegistrar.setBackground(new java.awt.Color(26, 177, 136));
        btnRegistrar.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar Egreso");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, -1, -1));

        ComboBoxTIPO_EGRESO.setFont(new java.awt.Font("Roboto Mono", 0, 24)); // NOI18N
        ComboBoxTIPO_EGRESO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comida", "Transporte", "Entretenimiento", "Servicios", "Gastos Varios" }));
        ComboBoxTIPO_EGRESO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        ComboBoxTIPO_EGRESO.setInheritsPopupMenu(true);
        ComboBoxTIPO_EGRESO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTIPO_EGRESOActionPerformed(evt);
            }
        });
        jPanel1.add(ComboBoxTIPO_EGRESO, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 290, -1));

        btnAtras.setBackground(new java.awt.Color(36, 48, 60));
        btnAtras.setFont(new java.awt.Font("Roboto Mono", 1, 36)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(0, 153, 153));
        btnAtras.setText("<-");
        btnAtras.setBorder(null);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Mono", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MONTO DEL EGRESO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        cbxDestinoFamiliar.setFont(new java.awt.Font("Roboto Mono", 0, 24)); // NOI18N
        cbxDestinoFamiliar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        cbxDestinoFamiliar.setInheritsPopupMenu(true);
        cbxDestinoFamiliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDestinoFamiliarActionPerformed(evt);
            }
        });
        jPanel1.add(cbxDestinoFamiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 290, -1));

        txtBienvenida.setBackground(new java.awt.Color(255, 255, 255));
        txtBienvenida.setFont(new java.awt.Font("Roboto Mono", 1, 30)); // NOI18N
        txtBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        txtBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBienvenida.setText("REGISTRAR EGRESO");
        jPanel1.add(txtBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 400, 50));

        jDateChooser.setBackground(new java.awt.Color(36, 48, 60));
        jDateChooser.setDateFormatString("yyyy-MM-dd");
        jDateChooser.setFont(new java.awt.Font("Roboto Mono", 0, 18)); // NOI18N
        jPanel1.add(jDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 290, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 390, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMONTO_EGRESOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMONTO_EGRESOActionPerformed

    }//GEN-LAST:event_txtMONTO_EGRESOActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void ComboBoxTIPO_EGRESOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxTIPO_EGRESOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxTIPO_EGRESOActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void cbxDestinoFamiliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDestinoFamiliarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDestinoFamiliarActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> ComboBoxTIPO_EGRESO;
    public javax.swing.JButton btnAtras;
    public javax.swing.JButton btnRegistrar;
    public javax.swing.JComboBox<Datos_Familia> cbxDestinoFamiliar;
    public com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel txtBienvenida;
    public javax.swing.JTextField txtMONTO_EGRESO;
    // End of variables declaration//GEN-END:variables
}
